### PR TITLE
Btt 256 mkstft32 v1 v2 v3 v4

### PR DESCRIPTION
**Pull request by Uz45**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### CODE REVIEW

**Comment by belese** [comment]
Hello,

i've got a MKS TFT32 v3 , and i can't manange to upload pics and fonts, so got a white screen.

I've the original boot loader, it seem to upload font and pics only if i've have a directory respectively named mks_font, and mks_pics on sd root dir.
and it upload only bin file, not bmp (it can be converted with [ image2LCD ](https://github.com/makerbase-mks/Software/tree/master/Image2LCD).

Has something i've missed to upload fonts and pics?

Thanks 

Johan

**Comment by Uz45** [comment]
Hi, @belese 

> Hello,
> 
> i've got a MKS TFT32 v3 , and i can't manange to upload pics and fonts, so got a white screen.
> 
> I've the original boot loader, it seem to upload font and pics only if i've have a directory respectively named mks_font, and mks_pics on sd root dir.
> and it upload only bin file, not bmp (it can be converted with [ image2LCD ](https://github.com/makerbase-mks/Software/tree/master/Image2LCD).
> 
> Has something i've missed to upload fonts and pics?
> 
> Thanks
> 
> Johan

  Folders named "mks_font", and "mks_pics" are used for the original firmware from MKS. To do this, the firmware correctly uses the "MKS" folder with the "bmp" and "font" folders located in it. Put the MKS folder in the SD root. The current version of the firmware is in the master branch.
https://github.com/Uz45/BIGTREETECH-TouchScreenFirmware/tree/master

  "MKS_32_V1_3.26.x.bin" should be renamed "mkstft28.bin" and placed in the root of the SD card. 
  You will also need the configuration file "config. ini". It should also be placed in the root of the SD.
  Fonts and images are available in three different themes. "THEME_Hybrid Red Menu Material theme", "THEME_The Round Miracle Menu Material theme", "THEME_Unified Menu Material theme"

**Comment by belese** [comment]
Ok thanks.
After open up the printer, it's a v4 and not a v3. All is working now.

**Comment by Uz45** [comment]
@belese
Then you better use the firmware from the main branch, it is updated more often. 
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware
Support for MKS TFT 32 V4. 0, already included in the main branch. I support this branch because of old versions V1, V2, V3.

**Comment by belese** [comment]
Hello, 
yes i've seen, 
and i manage to compile and run that branch fine.
Just one question about that branch, which folder did you use for pics? i've used the MKS folder from this branch as i don't know which one i have to use. (28 or 35)
And sorry for distubring, i have to open my printer to see it's a v4, as it was specified as a V3.

**Comment by Uz45** [comment]
@belese
Hi
> Just one question about that branch, which folder did you use for pics? i've used the MKS folder from this branch as i don't know which one i have to use. (28 or 35)

The "TFT28" folder is used for MKS TFT32.

**Pull request closed without merging**
